version: '3.4'

services:
  redis-node1:
    build:
      context: redis
    ports:
      - "6379:6379"
      - "16379:16379"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port, "6379", --cluster-announce-ip, "${ip}"]
  redis-node2:
    build:
      context: redis
    ports:
      - "6380:6380"
      - "16380:16380"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port, "6380", --cluster-announce-ip, "${ip}"]
  redis-node3:
    build:
      context: redis
    ports:
      - "6381:6381"
      - "16381:16381"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port, "6381", --cluster-announce-ip, "${ip}"]
  redis-node4:
    build:
      context: redis
    ports:
      - "6382:6382"
      - "16382:16382"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port, "6382", --cluster-announce-ip, "${ip}"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node5:
    build:
      context: redis
    ports:
      - "6383:6383"
      - "16383:16383"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port, "6383", --cluster-announce-ip, "${ip}"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node6:
    build:
      context: redis
    ports:
      - "6384:6384"
      - "16384:16384"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port, "6384", --cluster-announce-ip, "${ip}"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-cluster-creator:
    image: redis:6.0.3
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create ${ip}:6379 ${ip}:6380 ${ip}:6381 ${ip}:6382 ${ip}:6383 ${ip}:6384 --cluster-replicas 1']
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
